Feat: OPX3.1-dev1
open-switch/opx-sdi-sys pull request #25
Opened 2018-11-06 20:58 UTC by GarrickHe

* Bugfix: Removed assertion of delay entry in sdi cfg file
* Bugfix: Different optics type detected
* Bugfix: Fix endianess issue
* Update: Set default RX value to conform with dBm measurement

Signed-off-by: Garrick He <garrick_he@dell.com>

2018-11-07 20:04 UTC, jeffyin-dell requested changes

2018-11-07 20:04 UTC, jeffyin-dell commented on debian/changelog
> +  * Bugfix: Different optics type detected
Would be good to elaborate on this, as "different optics type detected" doesn't really sound like a bug.

2018-11-07 20:04 UTC, jeffyin-dell commented on inc/Makefile.am
> +	opx/sdi_ext_ctrl.h \
the spacing here looks off by 2 spaces

2018-11-07 20:04 UTC, jeff-yin commented on src/drivers/sdi_onie_eeprom.c
> +                err_mesg = "Invlaid value for PSU type in ONIE EEPROM vendor extension";
we're _introducing_ a typo here

2018-11-07 20:04 UTC, jeff-yin commented on src/hwcore/unittest_utils/pysdi.py
> +# THIS CODE IS PROVIDED ON AN #AS IS* BASIS, WITHOUT WARRANTIES OR
The changes in this file are incorrect and introduce typo/spacing errors.

2018-11-07 20:04 UTC, jeff-yin commented on src/hwcore/unittest_utils/sdi_shell.py
> +# THIS CODE IS PROVIDED ON AN #AS IS* BASIS, WITHOUT WARRANTIES OR
The changes in this file are incorrect and introduce typo/spacing errors.

2018-11-07 20:38 UTC, GarrickHe commented
Pull-request updated, HEAD is now 4d9280addd45b149245eb58374fe2719368ff365

2018-11-08 01:55 UTC, hpersh submitted a review, later dismissed

2018-11-08 05:52 UTC, GarrickHe commented
Pull-request updated, HEAD is now 085d17223cf7269b72e376dd1f24c80ac97d1481

2018-11-08 19:38 UTC, hpersh approved these changes

2018-11-08 19:41 UTC, jeffyin-dell approved these changes

2018-11-08 19:48 UTC, merged